#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap # stack

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  16
yabai -m config bottom_padding               16
yabai -m config left_padding                 16
yabai -m config right_padding                16
yabai -m config window_gap                   16

# manage windows based on the app
yabai -m rule --add label="Firefox" app="Firefox" manage=on
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='System Settings$' manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add title="^About This Mac$" manage=off
yabai -m rule --add app="^About This Mac$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^LiceCAP$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^ProtonVPN$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Omnivore$" manage=off
yabai -m rule --add label="Halloy" app="^Halloy$" manage=off
yabai -m rule --add label="Discord" app="Discord" manage=off
yabai -m rule --add label="Photos" app="Photos" manage=off
yabai -m rule --add label="Rhythm Doctor" app="Rhythm Doctor" manage=off
yabai -m rule --add label="1Password" app="1Password" manage=off

# make non-resizable windows float (maybe?)
# yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

echo "yabai configuration loaded.."
